### ISSUE TITLE
Замечания по паттерну "Наблюдатель"

### ISSUE THREAD

**Issue by alexey-malov** [minakovuri/ood#2]
- [x] Интерфейс IDisplayElement никто не использует. Поэтому он не нужен

**Comment by alexey-malov** [comment]
- [x] В интерфейсах не хватает виртуальных деструкторов

**Comment by alexey-malov** [comment]
- [x] Наблюдатели должны отписываться от субъекта при своём удалении

**Comment by alexey-malov** [comment]
```c++
class CInsideStatsDisplay : public IObserver<SInsideWeatherInfo>
{
public:
	typedef IObservable<SInsideWeatherInfo> ObservableType;
```

- [x] Лучше приватно унаследоваться

**Comment by alexey-malov** [comment]
- [x] Не надо делать getter-ы классу только ради тестов

**Comment by alexey-malov** [comment]
```c++
CInsideStatsDisplay::CInsideStatsDisplay(ObservableType& weatherDataRef)
{
	weatherDataRef.RegisterObserver(*this);
	m_observables.insert(&weatherDataRef);
}

CInsideStatsDisplay::~CInsideStatsDisplay()
{
	for (auto& observable : m_observables)
	{
		observable->RemoveObserver(*this);
	}
}
```

- [x] Зачем нужен set из одного элемента?

**Comment by alexey-malov** [comment]
```c++
class CInsideWeatherData
{
public:
	using DataChangeSignal = signals::signal<void(SInsideWeatherInfo data)>;
```

- [x] Лучше структуры передавать по константной ссылке

**Comment by alexey-malov** [comment]
- [x] В реализации с сигналами и слотами следует завести отдельные сигналы на каждый параметр

**Comment by minakovuri** [comment]
- [x] Добавить  отписку при удалении observable объекта
